'use client'

import robotoFont from "@/constants/localFonts";
import "./globals.css";
import { CssBaseline } from "@mui/material";
import { ThemeProvider } from "@mui/system";
import { darkTheme } from "./theme/themes";


export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				suppressHydrationWarning={true}
				className={`${robotoFont.variable} font-sans`}
			>
				{/* <ThemeProvider theme={darkTheme}> */}
					{/* <CssBaseline /> */}
					{children}
				{/* </ThemeProvider> */}
			</body>
		</html>
	);
}
