"use client";

import robotoFont from "@/constants/localFonts";
import "./globals.css";
import Header from "./Header";
import { Toaster } from "react-hot-toast";
import Providers from "./Providers";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				suppressHydrationWarning={true}
				className={`${robotoFont.variable} font-sans`}
			>
				<Header />
				<Providers>
					<main className="container">{children}</main>
				</Providers>
				<Toaster />
			</body>
		</html>
	);
}
